codecov:
  require_ci_to_pass: yes

coverage:
  precision: 1
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto   # Coverage target to pass; auto is base commit
        threshold: 2%  # Allow coverage to drop by this much and still pass


comment:
  layout: "diff,flags,tree"
